#!/bin/bash

if [[ `brew help >/dev/null 2>&1` != 0 ]]; then
    echo "You need to install homebrew!"
    echo "Go to http://brew.sh and follow the instructions"
    exit 1
fi

for pkg in qt5 libelf boost; do
    if [[ `brew list -1 | grep -q "^${pkg}\$"` != 0 ]]; then
        echo "Package '$pkg' is not installed"
        echo "Run: brew install $pkg"
    fi
done

QMCOMP=$(brew --prefix qt5)/bin/qmake

./configure

$QMCOMP elf2uarm.pro
make
make clean

$QMCOMP mkdev.pro
make
make clean

$QMCOMP qarm.pro
make
make clean
